# -*- coding: utf-8 -*-
"""Aprendizado de maquinas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wjxVwrBss_cSj0ay_TgxiDidNIXxeHJ2
"""

import pandas as pd

df = pd.read_csv('/content/Adult.csv')

print(df.head())

df.info()

print(df.isnull().sum())

print('Frequência para native-country:')
print(df['native-country'].value_counts())
print('\nFrequência para workclass:')
print(df['workclass'].value_counts())

mode_native_country = df['native-country'].mode()[0]
mode_workclass = df['workclass'].mode()[0]

df['native-country'] = df['native-country'].fillna(mode_native_country)
df['workclass'] = df['workclass'].fillna(mode_workclass)

print('Valores ausentes após preenchimento:')
print(df.isnull().sum())

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 6))
sns.countplot(y='native-country', data=df, order = df['native-country'].value_counts().index)
plt.title('Distribuição da Categoria native-country')
plt.xlabel('Contagem')
plt.ylabel('País de Origem')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
sns.countplot(y='workclass', data=df, order = df['workclass'].value_counts().index)
plt.title('Distribuição da Categoria workclass')
plt.xlabel('Contagem')
plt.ylabel('Classe de Trabalho')
plt.tight_layout()
plt.show()

import pandas as pd

# Preenchendo education com a moda
mode_edu = df['education'].mode()[0]
df['education'] = df['education'].fillna(mode_edu)

# Preenchendo occupation com 'Unknown' (já que são muitos valores)
df['occupation'] = df['occupation'].fillna('Unknown')

print('Valores ausentes finais:')
print(df.isnull().sum())

from sklearn.preprocessing import MinMaxScaler

# Identificando apenas colunas numéricas
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

# Criando o objeto de normalização
scaler = MinMaxScaler()

# Aplicando a normalização nas colunas numéricas
df.loc[:, numeric_cols] = scaler.fit_transform(df[numeric_cols])

print('Transformações aplicadas aos atributos numéricos (escala de 0 a 1):')
display(df.head())

df.to_csv('adult_limpo.csv', index=False)

sample_30_no_replace = df.sample(frac=0.30, replace=False, random_state=42)

print("Amostragem simples 30% sem reposição")
print("Número de linhas:", sample_30_no_replace.shape[0])

sample_30_replace = df.sample(frac=0.30, replace=True, random_state=42)

print("Amostragem simples 30% com reposição")
print("Número de linhas:", sample_30_replace.shape[0])

sample_50_no_replace = df.sample(frac=0.50, replace=False, random_state=42)

print("Amostragem simples 50% sem reposição")
print("Número de linhas:", sample_50_no_replace.shape[0])

sample_50_replace = df.sample(frac=0.50, replace=True, random_state=42)

print("Amostragem simples 50% com reposição")
print("Número de linhas:", sample_50_replace.shape[0])

sample_50_strat = df.groupby('class', group_keys=False).apply(
    lambda x: x.sample(frac=0.50, random_state=42),
    include_groups=False
)

print("Amostragem estratificada 50%")
print("Número de linhas:", sample_50_strat.shape[0])

display(sample_50_strat.head())

sample_70_no_replace = df.sample(frac=0.70, replace=False, random_state=42)

print("Amostragem simples 70% sem reposição")
print("Número de linhas:", sample_70_no_replace.shape[0])

sample_70_replace = df.sample(frac=0.70, replace=True, random_state=42)

print("Amostragem simples 70% com reposição")
print("Número de linhas:", sample_70_replace.shape[0])

sample_70_strat = df.groupby('class', group_keys=False).apply(
    lambda x: x.sample(frac=0.70, random_state=42),
    include_groups=False
)

print("Amostragem estratificada 70%")
print("Número de linhas:", sample_70_strat.shape[0])

display(sample_70_strat.head())

